"""empty message

Revision ID: 214f614f8c14
Revises: 
Create Date: 2022-07-05 11:05:29.219114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214f614f8c14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'requests_number')
    # ### end Alembic commands ###
