"""empty message

Revision ID: 273b5626f051
Revises: 214f614f8c14
Create Date: 2022-07-05 11:14:26.810117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '273b5626f051'
down_revision = '214f614f8c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'requests_number',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'requests_number',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
