"""empty message

Revision ID: 406224b59ba1
Revises: 53f91134085e
Create Date: 2022-07-25 09:46:10.127677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406224b59ba1'
down_revision = '53f91134085e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tb_apiusers', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_apiusers', type_='unique')
    # ### end Alembic commands ###
