"""empty message

Revision ID: 472b43f484d2
Revises: 3317a36a8479
Create Date: 2022-07-22 13:23:24.744393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '472b43f484d2'
down_revision = '3317a36a8479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_index('email', table_name='tb_apiusers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'tb_apiusers', ['email'], unique=False)
    op.create_table('tb_users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('requests_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('email', 'tb_users', ['email'], unique=False)
    # ### end Alembic commands ###
