"""empty message

Revision ID: 5eda5323fe08
Revises: 273854aed62c
Create Date: 2022-07-05 12:14:35.546105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eda5323fe08'
down_revision = '273854aed62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests_number', sa.Integer(), nullable=False))
    op.drop_column('tb_users', 'requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('tb_users', 'requests_number')
    # ### end Alembic commands ###
