"""empty message

Revision ID: 623edc50e0e2
Revises: c82a7ea44c01
Create Date: 2022-07-05 10:52:19.430831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623edc50e0e2'
down_revision = 'c82a7ea44c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'requests')
    # ### end Alembic commands ###
