"""empty message

Revision ID: 8d14b9503960
Revises: 623edc50e0e2
Create Date: 2022-07-05 10:53:55.218714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d14b9503960'
down_revision = '623edc50e0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests_number', sa.Integer(), nullable=False))
    op.drop_column('tb_users', 'requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tb_users', 'requests_number')
    # ### end Alembic commands ###
