"""empty message

Revision ID: 9f4a2e3a578e
Revises: 
Create Date: 2022-07-05 10:43:53.084863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f4a2e3a578e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'requests',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'requests',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
