"""empty message

Revision ID: a1b76933b0a2
Revises: 
Create Date: 2022-07-05 10:59:46.691894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1b76933b0a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'requests_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests_number', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
