"""empty message

Revision ID: a61de2b40b62
Revises: 5eda5323fe08
Create Date: 2022-07-06 16:41:37.711340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a61de2b40b62'
down_revision = '5eda5323fe08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cpf', table_name='tb_users')
    op.drop_column('tb_users', 'cpf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('cpf', mysql.VARCHAR(length=11), nullable=False))
    op.create_index('cpf', 'tb_users', ['cpf'], unique=False)
    # ### end Alembic commands ###
