"""empty message

Revision ID: aaf80df32b38
Revises: 26a26e05d335
Create Date: 2022-07-05 10:24:56.050482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aaf80df32b38'
down_revision = '26a26e05d335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'requests',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_users', 'requests',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
