"""empty message

Revision ID: c82a7ea44c01
Revises: 9f4a2e3a578e
Create Date: 2022-07-05 10:51:59.575446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c82a7ea44c01'
down_revision = '9f4a2e3a578e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'requests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
