"""empty message

Revision ID: ebe2a5afd9ca
Revises: 
Create Date: 2022-07-05 11:42:39.654521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe2a5afd9ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('requests_number', sa.Integer(), nullable=False, default=1))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'requests_number')
    # ### end Alembic commands ###
